name: PR Check

on:
  pull_request:
    branches:
      - "main"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: tup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Android Build
        run: ./gradlew assembleDebug

      - name: Unit Tests
        run: ./gradlew testDebug
        