name: PR Check

on:
  pull_request:
    branches:
      - "main"

jobs:
  Quality-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup JDK 17    
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create NetworkSecurity.cpp
        run: |
          cat <<EOF > ${{ github.workspace }}/core/network/implementation/src/main/cpp/com/will/core/network/security/NetworkSecurity.cpp
          #include "NetworkSecurity.h"
          
          #include <jni.h>
          #include <string>
          
          extern "C"
          jstring Java_com_will_core_network_implementation_security_NetworkSecurityImpl_getAccessToken(
                  JNIEnv *env,
                  __attribute__((unused)) jobject object
          ) {
              std::string access_token = "DUMMY_TOKEN";
              return env->NewStringUTF(access_token.c_str());
          }
          EOF

      - name: Android Build
        run: ./gradlew assembleDebug

      - name: Unit Tests
        run: ./gradlew testDebug

      - name: Run detekt
        run: ./gradlew runDetekt

      - name: Upload SARIF 
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif