name: Android Build and Deploy

on:
  push:
    branches:
      - 'release/*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out 
        uses: actions/checkout@v4

      - name: Setup JDK 17    
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Unit Tests
        run: ./gradlew testDebug

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/release/*' }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Wait for approval before deployment
        uses: hmarr/approve-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          git tag -a "release-$VERSION" -m "Release version $VERSION"
          git push origin "release-$VERSION"
          gh release create "release-$VERSION" app/build/outputs/apk/debug/app-debug.apk --title "Release $VERSION" --notes "Release generated on $(date)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}